# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=b'default.jpg', null=True, upload_to=b'profile_pics/'),
        ),
    ]
